"""add roles

Revision ID: 142209a5b351
Revises: 18c9501e8f6c
Create Date: 2024-05-25 14:25:53.561772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142209a5b351'
down_revision: Union[str, None] = '18c9501e8f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE role as ENUM('ADMIN', 'USER')")
    op.add_column('users', sa.Column('Role', sa.Enum('ADMIN', 'USER', name='role'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'Role')
    op.execute("DROP TYPE role")
    # ### end Alembic commands ###
