"""add table users

Revision ID: 3ba2339364a0
Revises: 66fe5beed437
Create Date: 2024-05-22 13:51:52.762325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba2339364a0'
down_revision: Union[str, None] = '66fe5beed437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Login', sa.String(length=20), nullable=False),
    sa.Column('Password', sa.String(length=20), nullable=False),
    sa.Column('Email', sa.String(length=20), nullable=False),
    sa.Column('Refresh_Token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True, on_update=sa.text('now()')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Login')
    )
    op.add_column('contacts', sa.Column('created_at', sa.Date(), nullable=True))
    op.add_column('contacts', sa.Column('updated_at', sa.Date(), nullable=True, on_update=sa.text('now()')))
    op.add_column('contacts', sa.Column('User_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contacts', 'users', ['User_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'User_id')
    op.drop_column('contacts', 'updated_at')
    op.drop_column('contacts', 'created_at')
    op.drop_table('users')
    # ### end Alembic commands ###
