"""Init

Revision ID: c662dd36e9fc
Revises: 
Create Date: 2024-05-16 13:22:00.752580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c662dd36e9fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=20), nullable=False),
    sa.Column('Surname', sa.String(length=20), nullable=False),
    sa.Column('Phone', sa.String(length=13), nullable=False),
    sa.Column('Email', sa.String(length=30), nullable=False),
    sa.Column('Birthday', sa.Date(), nullable=False),
    sa.Column('Additional_info', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Phone')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    # ### end Alembic commands ###
